sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YZsnzJaKp+GxaQ992h6P1lngqHeo00o26pWS8l8Q7UHE1grd7wkJMhhaQiAjqmcomWwjO/m8TLB3EvzHqIVOMOkg2Wt56ShiBoRwO1kXUUr2T03Uf26eJNoW8TyPWpjaB6cZ2+0QaFFyWfmnSSlLzTufJYpnvnwLHe1L27bpqCrV6DRV4279m7LdIwk8ewU1gSYnEvv0VhOadyhcDuHbeN7d9Rk3kE0omu6uQ+FpMGjsenjQqrfIzeHdAtgQHBOfwQ2XT7QmKLCm0BMfP6gSIHialxgii4xaZE2ZBSYIPpFC7QzTSPH46zAzuRzTBrnQwB2Hg2KXPSn6bGt/twDSXcA9Lwl2e3/v3LKDXc6jQ1zxP+Cjnj2PTyQHnOCQQ5jiPSXXOqavaY9tQnJPMBxJOaB9Q2tIMfsVbD34xJDxu2trJL+j+8el5Bk0RBtTxFXof9hWM0kDbj2Ayp06OOs7JDJRrBK8En2gH3L7IzGu7IUpU9AgTVL3UompFfff1+Kb2GghoMdUdl92zWxKhm74O0TIdVYBMmf/hMDSClwd9KQvWWYdrOVQXvAdlX8M8PR0BthtRCrEufzD0/QdoqClWGqY3IjAgfLcZ8qxPAYb9BB+3Knou7pFKSiorLg5KSkvs0pIpwv2ZlLIwpKr/19bRh8yooMV86m1mu4dRqN8PgE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Augsburg-Confession--13-The-confession-of-faith-which-was-submitted-to-His-Imperial-Majesty__275
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy